# Generated by Django 5.2.8 on 2025-12-04 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField(blank=True)),
                ('meta_description', models.TextField(blank=True)),
                ('h1', models.JSONField(default=list)),
                ('h2', models.JSONField(default=list)),
                ('h3', models.JSONField(default=list)),
                ('images', models.JSONField(default=list)),
                ('word_count', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('score_breakdown', models.JSONField(default=list)),
                ('rule_issues', models.JSONField(default=list)),
                ('raw_html_snippet', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('llm_model', models.CharField(blank=True, max_length=128)),
                ('llm_suggestions', models.JSONField(blank=True, default=dict)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='seo_app.page')),
            ],
        ),
    ]
