# Generated by Django 5.2.8 on 2025-12-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageanalysis',
            name='llm_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
