# Generated by Django 5.2.8 on 2025-12-10 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0002_pageanalysis_llm_generated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_authority', models.FloatField(blank=True, null=True)),
                ('estimated_monthly_traffic', models.IntegerField(blank=True, null=True)),
                ('total_backlinks', models.IntegerField(default=0)),
                ('referring_domains', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=500)),
                ('search_volume', models.IntegerField(default=0)),
                ('keyword_difficulty', models.IntegerField(default=0)),
                ('cpc', models.FloatField(default=0.0)),
                ('intent', models.CharField(choices=[('informational', 'Informational'), ('commercial', 'Commercial'), ('transactional', 'Transactional'), ('navigational', 'Navigational')], default='informational', max_length=20)),
                ('trend_score', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('keyword',)},
            },
        ),
        migrations.CreateModel(
            name='AuditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('issues_count', models.IntegerField(default=0)),
                ('critical_issues', models.IntegerField(default=0)),
                ('recorded_date', models.DateField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_history', to='seo_app.page')),
            ],
            options={
                'unique_together': {('page', 'recorded_date')},
            },
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords_in_common', models.IntegerField(default=0)),
                ('estimated_competitor_traffic', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competitor_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competing_against', to='seo_app.domain')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_of', to='seo_app.domain')),
            ],
            options={
                'unique_together': {('domain', 'competitor_domain')},
            },
        ),
        migrations.CreateModel(
            name='Backlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField()),
                ('source_domain', models.CharField(max_length=255)),
                ('anchor_text', models.TextField(blank=True)),
                ('link_type', models.CharField(choices=[('dofollow', 'DoFollow'), ('nofollow', 'NoFollow')], default='dofollow', max_length=20)),
                ('quality', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('target_url', models.URLField(blank=True, null=True)),
                ('source_domain_authority', models.FloatField(default=0)),
                ('found_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('target_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlinks', to='seo_app.domain')),
            ],
            options={
                'unique_together': {('target_domain', 'source_url', 'target_url')},
            },
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('word_count', models.IntegerField(default=0)),
                ('internal_links', models.IntegerField(default=0)),
                ('external_links', models.IntegerField(default=0)),
                ('seo_score', models.IntegerField(default=0)),
                ('engagement_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_pages', to='seo_app.domain')),
                ('primary_keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo_app.keyword')),
            ],
            options={
                'unique_together': {('domain', 'url')},
            },
        ),
        migrations.CreateModel(
            name='KeywordRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('url', models.URLField()),
                ('search_volume', models.IntegerField(default=0)),
                ('recorded_date', models.DateField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_rankings', to='seo_app.domain')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='seo_app.keyword')),
            ],
            options={
                'unique_together': {('domain', 'keyword', 'recorded_date')},
            },
        ),
        migrations.CreateModel(
            name='SiteMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organic_traffic', models.IntegerField(default=0)),
                ('organic_keywords', models.IntegerField(default=0)),
                ('domain_authority', models.FloatField(default=0)),
                ('total_backlinks', models.IntegerField(default=0)),
                ('referring_domains', models.IntegerField(default=0)),
                ('seo_health_score', models.IntegerField(default=0)),
                ('recorded_date', models.DateField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_history', to='seo_app.domain')),
            ],
            options={
                'unique_together': {('domain', 'recorded_date')},
            },
        ),
    ]
